name: CI/CD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bootstrap
        run: |
          ./bin/bootstrap
      - name: Setup
        run: |
          ./bin/setup
      - name: Test
        run: |
          ./bin/test
      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ./bin/setup-aws
      - name: Deploy (staging)
        if: github.ref != 'refs/heads/master'
        run: |
          ./bin/deploy-staging
      - name: Deploy (prod)
        if: github.ref == 'refs/heads/master'
        run: |
          ./bin/deploy-prod
